name: Setup Windows

description: Set up for windows jobs

inputs:
  github-secret:
    description: GitHub token
    required: true
  cuda-version:
    description: which cuda version to install, 'cpu' for none
    required: true

runs:
  using: composite
  steps:
    - name: Display EC2 information
      shell: bash
      run: .github/scripts/display_ec2_info.sh

    - name: "[FB EMPLOYEES] Enable SSH (Click me for login details)"
      uses: seemethere/add-github-ssh-key@v1
      with:
        GITHUB_TOKEN: ${{ inputs.github-secret }}

    # Needed for binary builds, see: https://github.com/pytorch/pytorch/issues/73339#issuecomment-1058981560
    - name: Enable long paths on Windows
      shell: powershell
      run: |
        Set-ItemProperty -Path "HKLM:\\SYSTEM\CurrentControlSet\Control\FileSystem" -Name "LongPathsEnabled" -Value 1

    - name: Install Visual Studio 2019 toolchain
      shell: powershell
      env:
        VS_VERSION: "16.8.6"
        INSTALL_WINDOWS_SDK: "1"
      run: |
        .\.circleci\scripts\vs_install.ps1

    - name: Install CUDA and CUDNN
      shell: bash
      if: inputs.cuda-version != 'cpu'
      env:
        CUDA_VERSION: ${{ inputs.cuda-version }}
      run: |
        .circleci/scripts/windows_cuda_install.sh
        .circleci/scripts/windows_cudnn_install.sh

    - name: Setup Python3
      uses: actions/setup-python@v2
      with:
        python-version: "3.x"
